---
title: "Talking Points"
author: "Joonsuk Kang"
date: "2020-03-24"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

### Papers

1. Hwang et al (2019) *Improving Subseasonal Forecasting in the Western U.S. with Machine Learning*
2. Chen and Banerjee (2018) *An Improved Analysis of Alternating Minimization for Structured Multi-Response Regression*
3. Scott (2019) *A Generalized Neyman-Pearson Criterion for Optimal Domain Adaptation*
4. Hanneke and Kpotufe (2019) *On the Value of Target Data in Transfer Learning*


### Questions/Thoughts

+ Climte Forecasting
  + Are we participating in the [Rodeo 2](https://www.topcoder.com/lp/rodeo2) (NOAA Subseasonal Climate Forecast Rodeo 2)?
  
+ Transfer Learning
  + The papers 3/4 are in binary classification settings. Possible extensions would be to 
    + establish similar results for regression setting, especially for the paper 4: value of target data
    + relate the general neyman-pearson criterion (in paper 3) to testing $H_0: \beta_i=0$ in high-dimensional setting to induce sparsity, i.e. interpreting the "controlled discovery rate" (CDR) criterion as sparsity-inducing criterion.
    
+ In our setting, why do we need transfer learning? How about treating LENS data as iid realizations of possible worlds and use simple methods such as nearest neighbors? "instance transfer" (with reweighting if necessary)

+ Other types of transfer learning: feature representation transfer, parameter transfer (from Pan and Yang 2009, A Survey on Transfer Learning)
  + the work with Abby seems to fall into the category of parameter transfer (estimate covariance matrix in )
  + Empirical Bayes seems one natural way to leverage LENS
    + 1) build a base model; 2) fit prior using LENS; 3) calculate posterior; 4) make prediction minimizing loss function (cosine distance)
  + in high-dimensional data, feature representation (model selection) and parameter estimation would be made simultaneously. --> Sparsity-inducing Empirical Bayes methods?

+ how to start writing (or working for) a theoretical paper in general?
